platform :ios, '8.0'

target 'ZHLBaseApp' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage','~> 3.8.1'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'NullSafe'
  pod 'Reachability'
  pod 'SVProgressHUD'	
  pod 'YYText'
  pod 'MJRefresh'
  pod 'DZNEmptyDataSet'
  pod 'JSPatch'
  pod 'BlocksKit'
  pod 'FMDB'
end
